# Site settings
title: Summer's Blog
email: victoriasqq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is Summer's personal blog. Write down what I see, what I experience and what I think.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  SummerSun
highlighter: pygments

# Build settings
markdown: kramdown
gems: ['jekyll-multiple-languages']
languages: ['en', 'cn']
language_default: 'en'
fill_default_content: false
