# Site settings
title: Summer Sun
email: victoriasqq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Summer's blog. Blog whatever I want to write.
baseurl: ""
github_username:  SummerSun
highlighter: pygments

# Build settings
markdown: kramdown
gems: ['jekyll-multiple-languages']
languages: ['en', 'cn']
language_default: 'en'
fill_default_content: false
